version: '3'
services:
    app:
        hostname: app
        stdin_open: true
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        ports:
            - '8000:8000'
